name: Annual Scrape and Upload

on:
  schedule:
    - cron: '0 0 23 8 *'

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy supabase python-dotenv pandas sqlalchemy

    - name: Run Scrapy spiders
      run: python runAll.py
